import { Portfolio, Discipline, Technology } from "./types";

export type TrendingPeriod = "day" | "week" | "month" | "allTime";

const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => hoursAgo(d * 24);

export const CATEGORY_TABS = [
  { slug: "all", label: "All Portfolios" },
  { slug: "minimalist", label: "Minimalist" },
  { slug: "dark-theme", label: "Dark Theme" },
  { slug: "interactive", label: "Interactive" },
  { slug: "creative", label: "Creative" },
  { slug: "modern-layouts", label: "Modern Layouts" },
  { slug: "engineering", label: "Engineering" },
] as const;

export const CATEGORIES = [
  {
    slug: "minimalist",
    label: "Minimalist Design Portfolios",
    count: "740+ Portfolios",
    cover: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "dark-theme",
    label: "Dark Themed Portfolios",
    count: "360+ Portfolios",
    cover: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "interactive",
    label: "Interactive Design Portfolios",
    count: "290+ Portfolios",
    cover: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "creative",
    label: "Creative Design Portfolios",
    count: "170+ Portfolios",
    cover: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "modern-layouts",
    label: "Modern Layout Design Portfolios",
    count: "90+ Portfolios",
    cover: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "engineering",
    label: "Engineering & Technical Showcase",
    count: "450+ Portfolios",
    cover: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
  },
] as const;

export const portfolios: Portfolio[] = [
  {
    id: "wallfolio-itsvg",
    primaryCategory: "interactive",
    styleCategory: "AI & Interactive",
    slug: "vivek-gupta-itsvg",
    url: "https://itsvg.in",
    title: "Vivek Gupta — Portfolio",
    tagline: "Software Engineer & Open Source Builder",
    description: "Personal website & developer portfolio of Vivek Gupta (itsvg).",
    owner: {
      username: "itsvg",
      displayName: "Vivek Gupta",
      githubUsername: "itsvg",
      avatarUrl: "https://avatar.vercel.sh/itsvg.png",
      role: "VERIFIED",
      bio: "Software Engineer & Builder",
      skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Node.js"],
    },
    status: "LIVE",
    discipline: ["ENGINEERING"],
    coverImage: "https://itsvg.in/og.png",
    qualityScore: 99,
    aiSummary: "Featured developer portfolio of Vivek Gupta: https://itsvg.in",
    viewCount: 2450,
    bookmarkCount: 142,
    likes: {
      day: 18,
      week: 85,
      month: 320,
      allTime: 1250,
    },
    technologies: [
      { id: "react", name: "React", category: "FRAMEWORK", source: "SELF_DECLARED" },
      { id: "nextjs", name: "Next.js", category: "FRAMEWORK", source: "SELF_DECLARED" },
      { id: "typescript", name: "TypeScript", category: "LANGUAGE", source: "SELF_DECLARED" },
      { id: "tailwindcss", name: "Tailwind CSS", category: "LIBRARY", source: "SELF_DECLARED" },
    ],
    caseStudies: [],
    testimonials: [],
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "p1",
    primaryCategory: "minimalist",
    slug: "paco-coursey",
    url: "https://paco.me",
    title: "Paco Coursey",
    owner: {
      username: "pacocoursey",
      displayName: "Paco Coursey",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "pacocoursey",
      skills: ["Interface Design", "React", "Next.js", "Design Systems"],
    },
    tagline: "Minimalist software interfaces and design engineering craft.",
    description: "Personal portfolio and digital garden of Paco Coursey.",
    status: "LIVE",
    discipline: ["DESIGN", "ENGINEERING"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fpaco.me?w=1200&h=750",
    qualityScore: 99,
    aiSummary: "Minimalist web interfaces and high-craft components.",
    viewCount: 38400,
    bookmarkCount: 2420,
    likes: { day: 140, week: 680, month: 1980, allTime: 4210 },
    verifiedAt: "2026-07-01T00:00:00Z",
    createdAt: hoursAgo(2),
    technologies: [
      { id: "t1", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
      { id: "t2", name: "React", category: "LIBRARY", source: "VERIFIED" },
      { id: "t3", name: "Tailwind CSS", category: "LIBRARY", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Minimalist",
  },
  {
    id: "p2",
    primaryCategory: "interactive",
    slug: "rauno-freiberg",
    url: "https://rauno.me",
    title: "Rauno Freiberg",
    owner: {
      username: "raunofreiberg",
      displayName: "Rauno Freiberg",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "raunofreiberg",
      skills: ["Interaction Design", "Fluid Motion", "Micro-interactions"],
    },
    tagline: "Interaction design, micro-details, and fluid user experiences.",
    description: "Personal portfolio and experiments of Rauno Freiberg.",
    status: "LIVE",
    discipline: ["DESIGN"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Frauno.me?w=1200&h=750",
    qualityScore: 98,
    aiSummary: "Fluid physics, subtle micro-interactions, and invisible craft.",
    viewCount: 34100,
    bookmarkCount: 2150,
    likes: { day: 110, week: 560, month: 1720, allTime: 3890 },
    verifiedAt: "2026-07-05T00:00:00Z",
    createdAt: hoursAgo(5),
    technologies: [
      { id: "t1", name: "React", category: "LIBRARY", source: "VERIFIED" },
      { id: "t2", name: "Framer Motion", category: "LIBRARY", source: "VERIFIED" },
      { id: "t3", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Interactive",
  },
  {
    id: "p3",
    primaryCategory: "creative",
    slug: "emil-kowalski",
    url: "https://emilkowal.ski",
    title: "Emil Kowalski",
    owner: {
      username: "emilkowalski",
      displayName: "Emil Kowalski",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "emilkowalski",
      skills: ["Animations", "Micro-interactions", "Design Engineering"],
    },
    tagline: "Animations on the web, tactile micro-interactions, and component engineering.",
    description: "Design engineer portfolio and interactive component showcases.",
    status: "LIVE",
    discipline: ["DESIGN", "ENGINEERING"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Femilkowal.ski?w=1200&h=750",
    qualityScore: 97,
    aiSummary: "Creative animation systems and UI engineering.",
    viewCount: 29800,
    bookmarkCount: 1890,
    likes: { day: 95, week: 490, month: 1480, allTime: 3420 },
    verifiedAt: "2026-07-10T00:00:00Z",
    createdAt: hoursAgo(8),
    technologies: [
      { id: "t1", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
      { id: "t2", name: "Framer Motion", category: "LIBRARY", source: "VERIFIED" },
      { id: "t3", name: "TypeScript", category: "LANGUAGE", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Creative",
  },
  {
    id: "p4",
    primaryCategory: "dark-theme",
    slug: "karri-saarinen",
    url: "https://karri.design",
    title: "Karri Saarinen",
    owner: {
      username: "karrisaarinen",
      displayName: "Karri Saarinen",
      avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "karrisaarinen",
      skills: ["Product Design", "Design Systems", "Creative Direction"],
    },
    tagline: "High-craft product design, dark UI systems, and software craftsmanship.",
    description: "Design leadership and high-craft software design showcase.",
    status: "LIVE",
    discipline: ["DESIGN", "PRODUCT"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fkarri.design?w=1200&h=750",
    qualityScore: 99,
    aiSummary: "Dark theme design systems and high-density productivity tools.",
    viewCount: 31200,
    bookmarkCount: 1960,
    likes: { day: 88, week: 460, month: 1390, allTime: 3180 },
    verifiedAt: "2026-07-12T00:00:00Z",
    createdAt: hoursAgo(12),
    technologies: [
      { id: "t1", name: "Figma", category: "DESIGN_TOOL", source: "VERIFIED" },
      { id: "t2", name: "React", category: "LIBRARY", source: "VERIFIED" },
      { id: "t3", name: "CSS Modules", category: "LIBRARY", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Dark Theme",
  },
  {
    id: "p5",
    primaryCategory: "engineering",
    slug: "lee-robinson",
    url: "https://leerob.io",
    title: "Lee Robinson",
    owner: {
      username: "leerob",
      displayName: "Lee Robinson",
      avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "leerob",
      skills: ["Next.js", "React", "Developer Experience"],
    },
    tagline: "Product leadership, modern web architecture, and developer education.",
    description: "Personal website, essays, and Next.js engineering showcases.",
    status: "LIVE",
    discipline: ["ENGINEERING", "PRODUCT"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fleerob.io?w=1200&h=750",
    qualityScore: 98,
    aiSummary: "Modern Next.js web architectures and developer tool patterns.",
    viewCount: 27500,
    bookmarkCount: 1650,
    likes: { day: 76, week: 410, month: 1220, allTime: 2950 },
    verifiedAt: "2026-07-15T00:00:00Z",
    createdAt: hoursAgo(15),
    technologies: [
      { id: "t1", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
      { id: "t2", name: "React", category: "LIBRARY", source: "VERIFIED" },
      { id: "t3", name: "TypeScript", category: "LANGUAGE", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Engineering",
  },
  {
    id: "p6",
    primaryCategory: "modern-layouts",
    slug: "brian-lovin",
    url: "https://brianlovin.com",
    title: "Brian Lovin",
    owner: {
      username: "brianlovin",
      displayName: "Brian Lovin",
      avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "brianlovin",
      skills: ["Product Design", "Mobile UI", "Web Applications"],
    },
    tagline: "Product designer building collaborative tools and mobile experiences.",
    description: "Design portfolio, side projects, and apps by Brian Lovin.",
    status: "LIVE",
    discipline: ["DESIGN", "PRODUCT"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fbrianlovin.com?w=1200&h=750",
    qualityScore: 96,
    aiSummary: "Clean modern product layouts and collaborative mobile UI.",
    viewCount: 24100,
    bookmarkCount: 1420,
    likes: { day: 65, week: 340, month: 1080, allTime: 2680 },
    verifiedAt: "2026-08-01T00:00:00Z",
    createdAt: hoursAgo(18),
    technologies: [
      { id: "t1", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
      { id: "t2", name: "React", category: "LIBRARY", source: "VERIFIED" },
      { id: "t3", name: "Figma", category: "DESIGN_TOOL", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Modern Layouts",
  },
  {
    id: "p7",
    primaryCategory: "interactive",
    slug: "pedro-duarte",
    url: "https://ped.ro",
    title: "Pedro Duarte",
    owner: {
      username: "pedroduarte",
      displayName: "Pedro Duarte",
      avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "peduarte",
      skills: ["Design Systems", "Accessibility", "Radix UI"],
    },
    tagline: "Design systems, accessible primitives, and fluid browser experiences.",
    description: "Design technologist portfolio and interactive experiments.",
    status: "LIVE",
    discipline: ["DESIGN", "ENGINEERING"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fped.ro?w=1200&h=750",
    qualityScore: 97,
    aiSummary: "Accessible design primitives and fluid UI components.",
    viewCount: 22800,
    bookmarkCount: 1380,
    likes: { day: 58, week: 310, month: 960, allTime: 2450 },
    verifiedAt: "2026-08-05T00:00:00Z",
    createdAt: hoursAgo(22),
    technologies: [
      { id: "t1", name: "React", category: "LIBRARY", source: "VERIFIED" },
      { id: "t2", name: "Radix UI", category: "LIBRARY", source: "VERIFIED" },
      { id: "t3", name: "TypeScript", category: "LANGUAGE", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Interactive",
  },
  {
    id: "p8",
    primaryCategory: "engineering",
    slug: "takuya-matsuyama",
    url: "https://craftz.dog",
    title: "Takuya Matsuyama",
    owner: {
      username: "craftzdog",
      displayName: "Takuya Matsuyama",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "craftzdog",
      skills: ["Three.js", "React Native", "Next.js"],
    },
    tagline: "Crafting digital tools, 3D interactive portfolio, and indie software.",
    description: "3D interactive homepage and projects of Takuya Matsuyama.",
    status: "LIVE",
    discipline: ["ENGINEERING", "DESIGN"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fcraftz.dog?w=1200&h=750",
    qualityScore: 98,
    aiSummary: "3D voxel art, WebGL interactive canvas, and indie hacker craft.",
    viewCount: 26400,
    bookmarkCount: 1540,
    likes: { day: 62, week: 330, month: 990, allTime: 2390 },
    verifiedAt: "2026-08-08T00:00:00Z",
    createdAt: daysAgo(2),
    technologies: [
      { id: "t1", name: "Three.js", category: "LIBRARY", source: "VERIFIED" },
      { id: "t2", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
      { id: "t3", name: "Chakra UI", category: "LIBRARY", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Engineering",
  },
  {
    id: "p9",
    primaryCategory: "dark-theme",
    slug: "shu-ding",
    url: "https://shud.in",
    title: "Shu Ding",
    owner: {
      username: "shuding",
      displayName: "Shu Ding",
      avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "shuding",
      skills: ["Algorithm Visualizations", "Next.js", "SWR"],
    },
    tagline: "Data structures, algorithm visualizations, and minimal interface engineering.",
    description: "Designer and software engineer personal site and visual algorithms.",
    status: "LIVE",
    discipline: ["DESIGN", "ENGINEERING"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fshud.in?w=1200&h=750",
    qualityScore: 96,
    aiSummary: "Generative canvas algorithms and minimalist dark UI.",
    viewCount: 19800,
    bookmarkCount: 1210,
    likes: { day: 45, week: 240, month: 810, allTime: 2120 },
    verifiedAt: "2026-08-10T00:00:00Z",
    createdAt: daysAgo(3),
    technologies: [
      { id: "t1", name: "React", category: "LIBRARY", source: "VERIFIED" },
      { id: "t2", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
      { id: "t3", name: "Canvas API", category: "PLATFORM", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Dark Theme",
  },
  {
    id: "p10",
    primaryCategory: "minimalist",
    slug: "delba-oliveira",
    url: "https://delba.dev",
    title: "Delba de Oliveira",
    owner: {
      username: "delbaoliveira",
      displayName: "Delba de Oliveira",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "delbaoliveira",
      skills: ["React Server Components", "Next.js", "Web Performance"],
    },
    tagline: "Interactive developer tutorials, Next.js architecture, and minimal UI craft.",
    description: "Developer experience engineer portfolio and visual tutorials.",
    status: "LIVE",
    discipline: ["ENGINEERING", "DESIGN"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fdelba.dev?w=1200&h=750",
    qualityScore: 95,
    aiSummary: "Interactive React Server Components diagrams and clean tutorials.",
    viewCount: 18500,
    bookmarkCount: 1140,
    likes: { day: 42, week: 220, month: 760, allTime: 1980 },
    verifiedAt: "2026-08-11T00:00:00Z",
    createdAt: daysAgo(4),
    technologies: [
      { id: "t1", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
      { id: "t2", name: "TypeScript", category: "LANGUAGE", source: "VERIFIED" },
      { id: "t3", name: "Tailwind CSS", category: "LIBRARY", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Minimalist",
  },
  {
    id: "p11",
    primaryCategory: "creative",
    slug: "linus-rogge",
    url: "https://linusrogge.com",
    title: "Linus Rogge",
    owner: {
      username: "linusrogge",
      displayName: "Linus Rogge",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "linusrogge",
      skills: ["Interaction Design", "Framer", "WebGL", "Three.js"],
    },
    tagline: "Tactile web interactions, motion prototyping, and generative shaders.",
    description: "Interface designer and technologist portfolio.",
    status: "LIVE",
    discipline: ["DESIGN", "ENGINEERING"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Flinusrogge.com?w=1200&h=750",
    qualityScore: 94,
    aiSummary: "Tactile motion prototypes and generative shaders.",
    viewCount: 16900,
    bookmarkCount: 980,
    likes: { day: 36, week: 190, month: 690, allTime: 1840 },
    verifiedAt: "2026-08-12T00:00:00Z",
    createdAt: daysAgo(5),
    technologies: [
      { id: "t1", name: "Framer", category: "DESIGN_TOOL", source: "VERIFIED" },
      { id: "t2", name: "Three.js", category: "LIBRARY", source: "VERIFIED" },
      { id: "t3", name: "GLSL", category: "LANGUAGE", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Creative",
  },
  {
    id: "p12",
    primaryCategory: "modern-layouts",
    slug: "alex-carpenter",
    url: "https://alexcarpenter.me",
    title: "Alex Carpenter",
    owner: {
      username: "alexcarpenter",
      displayName: "Alex Carpenter",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      role: "VERIFIED",
      githubUsername: "alexcarpenter",
      skills: ["CSS Layouts", "Accessibility", "Design Systems"],
    },
    tagline: "Modern CSS layouts, design engineering, and accessible component architectures.",
    description: "Design engineer portfolio and modern CSS craft.",
    status: "LIVE",
    discipline: ["DESIGN", "ENGINEERING"],
    coverImage: "https://s0.wp.com/mshots/v1/https%3A%2F%2Falexcarpenter.me?w=1200&h=750",
    qualityScore: 95,
    aiSummary: "Accessible CSS Grid layouts and modern design tokens.",
    viewCount: 15400,
    bookmarkCount: 920,
    likes: { day: 31, week: 170, month: 620, allTime: 1710 },
    verifiedAt: "2026-08-13T00:00:00Z",
    createdAt: daysAgo(6),
    technologies: [
      { id: "t1", name: "Next.js", category: "FRAMEWORK", source: "VERIFIED" },
      { id: "t2", name: "CSS Grid", category: "PLATFORM", source: "VERIFIED" },
      { id: "t3", name: "TypeScript", category: "LANGUAGE", source: "VERIFIED" },
    ],
    caseStudies: [],
    testimonials: [],
    styleCategory: "Modern Layouts",
  },
];

export const disciplineFacets: Discipline[] = [
  "DESIGN",
  "ENGINEERING",
  "PRODUCT",
  "DATA",
  "OTHER",
];

export const technologyFacets: string[] = [
  "Figma",
  "Framer",
  "React",
  "Next.js",
  "TypeScript",
  "Three.js",
  "Tailwind CSS",
  "WebGL",
  "Rive",
  "Python",
  "Rust",
];

export function getRecentlyAdded(limit = 8): Portfolio[] {
  return [...portfolios]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
}

export function getTrending(period: TrendingPeriod = "week", limit = 10): Portfolio[] {
  return [...portfolios]
    .sort((a, b) => b.likes[period] - a.likes[period])
    .slice(0, limit);
}

export function getMostLikedPortfolios(limit = 8): Portfolio[] {
  return [...portfolios]
    .sort((a, b) => b.likes.allTime - a.likes.allTime)
    .slice(0, limit);
}

export function getCategoryCounts() {
  return CATEGORIES.map((cat) => ({
    slug: cat.slug,
    name: cat.label,
    count: portfolios.filter((p) => p.primaryCategory === cat.slug).length || 1,
    cover: cat.cover,
    badgeText: cat.count,
  }));
}

export function getPortfolioBySlug(slug: string): Portfolio | undefined {
  return portfolios.find((p) => p.slug === slug);
}

export function getSimilarPortfolios(portfolio: Portfolio, limit = 3): Portfolio[] {
  return portfolios
    .filter((p) => p.id !== portfolio.id)
    .filter((p) =>
      p.primaryCategory === portfolio.primaryCategory ||
      p.discipline.some((d) => portfolio.discipline.includes(d))
    )
    .slice(0, limit);
}
